"use client"

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { MessageSquare, FileText, BarChart3 } from "lucide-react"
import { Badge } from "@/components/ui/badge"
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar"

export function RecentActivity() {
  const activities = [
    {
      type: "chat",
      title: "Technical Diligence Discussion",
      desc: "Can you analyze their tech stack and scalability?",
      user: "Sarah Chen",
      time: "2 hours ago",
      msgs: 45,
      icon: MessageSquare,
      initials: "SC",
    },
    {
      type: "report",
      title: "Market Analysis Report",
      desc: "Generated by Amy",
      date: "2024-01-11",
      badge: "Market Research",
      icon: BarChart3,
    },
    {
      type: "chat",
      title: "Market Size Analysis",
      desc: "What's the TAM for value-based care software?",
      user: "Michael Park",
      time: "5 hours ago",
      msgs: 32,
      icon: MessageSquare,
      initials: "MP",
    },
    {
      type: "report",
      title: "Technical Due Diligence Summary",
      desc: "Generated by Amy",
      date: "2024-01-10",
      badge: "Technical Review",
      icon: FileText,
    },
    {
      type: "chat",
      title: "Financial Model Review",
      desc: "Build a 5-year revenue projection model",
      user: "Sarah Chen",
      time: "1 day ago",
      msgs: 28,
      icon: MessageSquare,
      initials: "SC",
    },
  ]

  return (
    <div className="grid md:grid-cols-2 gap-4">
       <Card className="h-[200px] flex flex-col overflow-hidden">
          <CardHeader>
             <CardTitle className="text-base font-semibold">Recent Chats</CardTitle>
          </CardHeader>
          <CardContent className="space-y-0 flex-1 overflow-y-auto">
             {activities.filter(a => a.type === "chat").map((item, i) => (
                <div key={i} className="flex items-start gap-4 p-4 hover:bg-muted/50 transition-colors cursor-pointer border-b last:border-0 -mx-6 px-6 last:pb-0 first:pt-0">
                   <Avatar className="h-8 w-8">
                      <AvatarFallback className="text-xs bg-primary/10 text-primary">{item.initials}</AvatarFallback>
                   </Avatar>
                   <div className="flex-1 space-y-1">
                      <div className="flex items-center justify-between">
                         <p className="font-medium text-sm">{item.title}</p>
                         <Badge variant="secondary" className="rounded-sm font-normal text-[10px] h-5 px-1.5">{item.msgs} msgs</Badge>
                      </div>
                      <p className="text-xs text-muted-foreground line-clamp-1">{item.desc}</p>
                      <div className="flex items-center gap-2 text-xs text-muted-foreground mt-1.5">
                         <span className="font-medium text-foreground">{item.user}</span>
                         <span>•</span>
                         <span>{item.time}</span>
                      </div>
                   </div>
                </div>
             ))}
          </CardContent>
       </Card>

       <Card className="h-[200px] flex flex-col overflow-hidden">
          <CardHeader>
             <CardTitle className="text-base font-semibold">Recent Reports</CardTitle>
          </CardHeader>
          <CardContent className="space-y-0 flex-1 overflow-y-auto">
             {activities.filter(a => a.type === "report").map((item, i) => (
                <div key={i} className="flex items-start gap-4 p-4 hover:bg-muted/50 transition-colors cursor-pointer border-b last:border-0 -mx-6 px-6 last:pb-0 first:pt-0">
                    <div className="h-8 w-8 rounded-lg bg-primary/10 text-primary flex items-center justify-center shrink-0">
                       <item.icon className="h-4 w-4" />
                    </div>
                    <div className="flex-1 space-y-1">
                       <div className="flex items-center justify-between">
                          <p className="font-medium text-sm">{item.title}</p>
                          <Badge variant="outline" className="text-[10px] h-5 font-normal">{item.badge}</Badge>
                       </div>
                       <p className="text-xs text-muted-foreground">{item.desc}</p>
                       <p className="text-xs text-muted-foreground mt-1">{item.date}</p>
                    </div>
                </div>
             ))}
          </CardContent>
       </Card>
    </div>
  )
}
