"use client"

import * as React from "react"
import { toast } from "sonner"
import { FileText } from "lucide-react"

import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog"
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  CardDescription,
  CardFooter,
} from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { ChatInput } from "@/components/chat-input"
import { Badge } from "@/components/ui/badge"

const reports = [
  {
    id: "1",
    title: "Market Analysis Report",
    date: "2024-01-11",
    type: "Market Research",
    description: "Comprehensive analysis of the target market, including TAM, SAM, and SOM estimations.",
    content: "This is the full content of the Market Analysis Report. It contains detailed insights into market trends, growth drivers, and potential barriers to entry...",
  },
  {
    id: "2",
    title: "Technical Due Diligence Summary",
    date: "2024-01-10",
    type: "Technical Review",
    description: "Evaluation of the technology stack, code quality, and scalability of the platform.",
    content: "The Technical Due Diligence Summary highlights the robustness of the current architecture. Key findings include...",
  },
  {
    id: "3",
    title: "Competitive Landscape Analysis",
    date: "2024-01-09",
    type: "Competitive Analysis",
    description: "Deep dive into key competitors, their market share, and product differentiation strategies.",
    content: "Our analysis of the competitive landscape reveals a fragmented market with several niche players...",
  },
]

interface ReportModalProps {
  open: boolean
  onOpenChange: (open: boolean) => void
}

export function ReportModal({ open, onOpenChange }: ReportModalProps) {
  const [selectedReport, setSelectedReport] = React.useState<typeof reports[0] | null>(null)

  const handleSend = (message: string) => {
    console.log("Sending message regarding report:", message)
    toast("Amy is analyzing your request about this report...")
  }

  const handleBack = () => {
    setSelectedReport(null)
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="overflow-hidden p-0 md:max-h-[600px] md:max-w-[800px] lg:max-w-[900px] flex flex-col">
        <DialogHeader className="px-6 py-4 border-b">
          <DialogTitle>{selectedReport ? selectedReport.title : "Reports Repository"}</DialogTitle>
          <DialogDescription>
            {selectedReport 
              ? `Generated on ${selectedReport.date} • ${selectedReport.type}`
              : "Access and review reports generated by Amy."}
          </DialogDescription>
        </DialogHeader>

        <div className="flex-1 overflow-y-auto bg-muted/10 p-6">
          {!selectedReport ? (
            <div className="grid gap-4 md:grid-cols-2">
              {reports.map((report) => (
                <Card 
                  key={report.id} 
                  className="cursor-pointer hover:shadow-md transition-shadow"
                  onClick={() => setSelectedReport(report)}
                >
                  <CardHeader className="pb-3">
                    <div className="flex justify-between items-start">
                      <div className="space-y-1">
                        <CardTitle className="text-base">{report.title}</CardTitle>
                        <CardDescription>{report.date}</CardDescription>
                      </div>
                      <Badge variant="outline">{report.type}</Badge>
                    </div>
                  </CardHeader>
                  <CardContent>
                    <p className="text-sm text-muted-foreground line-clamp-2">
                      {report.description}
                    </p>
                  </CardContent>
                  <CardFooter className="pt-0">
                    <Button variant="ghost" size="sm" className="ml-auto">View Report</Button>
                  </CardFooter>
                </Card>
              ))}
            </div>
          ) : (
            <div className="space-y-6">
              <div className="bg-background rounded-lg border p-6 shadow-sm min-h-[300px]">
                <div className="prose prose-sm max-w-none">
                  <p>{selectedReport.content}</p>
                  <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                  </p>
                  <p>
                    Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                  </p>
                </div>
              </div>
            </div>
          )}
        </div>

        {selectedReport ? (
          <div className="border-t bg-background p-4 flex flex-col gap-4">
             <div className="flex justify-between items-center px-2">
                <Button variant="ghost" size="sm" onClick={handleBack}>
                  ← Back to Reports
                </Button>
             </div>
             <ChatInput onSend={handleSend} />
          </div>
        ) : (
           <div className="border-t bg-background p-4 flex justify-end">
              <Button variant="outline" onClick={() => onOpenChange(false)}>Close</Button>
           </div>
        )}
      </DialogContent>
    </Dialog>
  )
}
