import { SourcingFeed, Opportunity } from "./types"

export const mockFeeds: SourcingFeed[] = [
  {
    id: "feed-1",
    name: "AI Infrastructure",
    description: "Early-stage AI/ML infrastructure companies",
    criteria: {
      sectors: ["AI/ML", "Developer Tools", "Infrastructure"],
      locations: ["San Francisco", "New York", "Remote"],
      fundingStages: ["Pre-seed", "Seed"],
      keywords: ["LLM", "inference", "training", "MLOps"],
    },
    newCount: 12,
    totalCount: 47,
    createdAt: "2024-01-15",
    lastUpdated: "2024-12-19",
  },
  {
    id: "feed-2",
    name: "Climate Tech",
    description: "Sustainable energy and climate solutions",
    criteria: {
      sectors: ["CleanTech", "Energy", "Sustainability"],
      locations: ["Europe", "US"],
      fundingStages: ["Seed", "Series A"],
      keywords: ["carbon", "renewable", "storage", "grid"],
    },
    newCount: 8,
    totalCount: 31,
    createdAt: "2024-02-20",
    lastUpdated: "2024-12-18",
  },
  {
    id: "feed-3",
    name: "Fintech B2B",
    description: "B2B financial infrastructure",
    criteria: {
      sectors: ["Fintech", "Payments", "Banking"],
      locations: ["US", "UK"],
      fundingStages: ["Seed", "Series A"],
      keywords: ["payments", "treasury", "banking API"],
    },
    newCount: 5,
    totalCount: 22,
    createdAt: "2024-03-10",
    lastUpdated: "2024-12-17",
  },
]

export const mockOpportunities: Opportunity[] = [
  // AI Infrastructure Feed
  {
    id: "opp-1",
    feedId: "feed-1",
    companyName: "NeuralFlow AI",
    initials: "NF",
    description: "Building next-gen inference optimization for LLMs with 10x cost reduction",
    sector: "AI/ML",
    location: "San Francisco, CA",
    fundingStage: "Seed",
    matchScore: 94,
    whyMatched: "Strong match on LLM infrastructure focus. Founded by ex-Google Brain researchers. Recent traction with enterprise customers.",
    foundDate: "2024-12-19",
    website: "neuralflow.ai",
    founders: ["Sarah Chen", "Mike Rodriguez"],
    employeeCount: "5-10",
    status: "new",
  },
  {
    id: "opp-2",
    feedId: "feed-1",
    companyName: "VectorDB Labs",
    initials: "VL",
    description: "Purpose-built vector database for AI applications with sub-millisecond latency",
    sector: "Developer Tools",
    location: "New York, NY",
    fundingStage: "Pre-seed",
    matchScore: 91,
    whyMatched: "Addresses key infrastructure gap in AI stack. Technical founders with distributed systems background.",
    foundDate: "2024-12-18",
    website: "vectordblabs.com",
    founders: ["James Park"],
    employeeCount: "1-5",
    status: "new",
  },
  {
    id: "opp-3",
    feedId: "feed-1",
    companyName: "MLPipe",
    initials: "MP",
    description: "Automated ML pipeline orchestration for enterprise teams",
    sector: "MLOps",
    location: "Remote",
    fundingStage: "Seed",
    matchScore: 87,
    whyMatched: "Growing MLOps market. Strong open-source community. 3x MoM growth in users.",
    foundDate: "2024-12-17",
    website: "mlpipe.io",
    founders: ["Lisa Wang", "Tom Harris"],
    employeeCount: "10-20",
    status: "new",
  },
  {
    id: "opp-4",
    feedId: "feed-1",
    companyName: "TrainCloud",
    initials: "TC",
    description: "Distributed training infrastructure reducing model training time by 5x",
    sector: "Infrastructure",
    location: "San Francisco, CA",
    fundingStage: "Seed",
    matchScore: 85,
    whyMatched: "Solves major pain point in AI development. Technical team from Meta AI.",
    foundDate: "2024-12-16",
    website: "traincloud.dev",
    founders: ["Alex Kim"],
    employeeCount: "5-10",
    status: "new",
  },
  {
    id: "opp-5",
    feedId: "feed-1",
    companyName: "PromptForge",
    initials: "PF",
    description: "Enterprise prompt engineering and management platform",
    sector: "AI/ML",
    location: "Austin, TX",
    fundingStage: "Pre-seed",
    matchScore: 82,
    whyMatched: "Emerging category. Strong early customer traction with Fortune 500.",
    foundDate: "2024-12-15",
    founders: ["Rachel Green"],
    employeeCount: "1-5",
    status: "new",
  },
  {
    id: "opp-6",
    feedId: "feed-1",
    companyName: "InferenceEdge",
    initials: "IE",
    description: "Edge inference optimization for IoT and mobile devices",
    sector: "AI/ML",
    location: "Seattle, WA",
    fundingStage: "Seed",
    matchScore: 79,
    whyMatched: "Unique positioning in edge AI. Partnership with major chip manufacturer.",
    foundDate: "2024-12-14",
    founders: ["David Chen", "Emma Wilson"],
    employeeCount: "5-10",
    status: "new",
  },
  // Climate Tech Feed
  {
    id: "opp-7",
    feedId: "feed-2",
    companyName: "CarbonCapture Inc",
    initials: "CC",
    description: "Direct air capture technology with 50% lower cost than competitors",
    sector: "CleanTech",
    location: "Denver, CO",
    fundingStage: "Seed",
    matchScore: 92,
    whyMatched: "Breakthrough technology in carbon capture. Strong IP portfolio.",
    foundDate: "2024-12-19",
    founders: ["Maria Santos"],
    employeeCount: "10-20",
    status: "new",
  },
  {
    id: "opp-8",
    feedId: "feed-2",
    companyName: "GridBalance",
    initials: "GB",
    description: "AI-powered grid management for renewable energy integration",
    sector: "Energy",
    location: "Berlin, Germany",
    fundingStage: "Series A",
    matchScore: 88,
    whyMatched: "Critical infrastructure for energy transition. Contracts with 3 European utilities.",
    foundDate: "2024-12-18",
    founders: ["Hans Mueller", "Sophie Laurent"],
    employeeCount: "20-50",
    status: "new",
  },
  // Fintech Feed
  {
    id: "opp-9",
    feedId: "feed-3",
    companyName: "TreasuryOS",
    initials: "TO",
    description: "Modern treasury management platform for SMBs",
    sector: "Fintech",
    location: "New York, NY",
    fundingStage: "Seed",
    matchScore: 90,
    whyMatched: "Underserved SMB segment. Strong product-market fit signals.",
    foundDate: "2024-12-19",
    founders: ["Michael Brown", "Jennifer Lee"],
    employeeCount: "10-20",
    status: "new",
  },
  {
    id: "opp-10",
    feedId: "feed-3",
    companyName: "PayRails",
    initials: "PR",
    description: "Payment orchestration layer for multi-PSP management",
    sector: "Payments",
    location: "London, UK",
    fundingStage: "Series A",
    matchScore: 86,
    whyMatched: "Growing enterprise demand for payment flexibility. 200% YoY revenue growth.",
    foundDate: "2024-12-17",
    founders: ["Oliver Smith"],
    employeeCount: "20-50",
    status: "new",
  },
]


